In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [58]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [60]:
df.total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [61]:
x = df.drop('total_bill', axis=1)
y = df['total_bill']

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=1)

In [63]:
#handling the missing value
#data encoding
#feature scaling


from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [64]:
df.sample()

     total_bill  tip     sex smoker   day   time  size
128       11.38  2.0  Female     No  Thur  Lunch     2

In [65]:
cat_cols = ["sex", "smoker", "day", "time"]
num_cols = ["tip", "size"]

In [66]:
#feature engineering automation using pipeline and column transformer

num_pipeline = Pipeline(steps = [('imputation', SimpleImputer(strategy='median')),
                  ('scaling', StandardScaler()),])

cat_pipeline = Pipeline(steps = [('imputation', SimpleImputer(strategy='most_frequent')),
                  ('encoding', OneHotEncoder()),])

In [67]:
preprocessor = ColumnTransformer([('num_pipeline', num_pipeline, num_cols),
                        ('cat_pipeline', cat_pipeline, cat_cols)])

In [68]:
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [69]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

In [70]:
models = {"MLR": LinearRegression(),
          "Support vector Regressor": SVR(),
          "Random forest regressor": RandomForestRegressor()}

In [72]:
for i in range(len(models)):
    print(list(models.values())[i])

LinearRegression()
SVR()
RandomForestRegressor()

In [74]:
from sklearn.metrics import r2_score
evaluation = {}
def model_train_eval(x_train,x_test, y_train, y_test):
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(x_train,y_train)
        y_pred = model.predict(x_test)
        model_score = r2_score(y_test,y_pred)
        evaluation[list(models.keys())[i]] = model_score
    return evaluation

In [75]:
model_train_eval(x_train,x_test,y_train,y_test)

{'MLR': 0.5033350544132275,
 'Support vector Regressor': 0.3429078257481145,
 'Random forest regressor': 0.4291730604458738}